### ISSUE TITLE
Question on the octicons SVG

### ISSUE THREAD

**Issue by WebAssemblyMan** [microsoft/vscode-octicons-font#10]
Nice work! May I ask if the SVGs are updated in anyway? I tried converting from the SVGs from Primer/octicons. But they somehow would not work. Is it possible to let me know what changes to the SVGs are required? Thanks.

**Comment by miguelsolorio** [comment]
These SVGs are definitely modified to work with the icon font tool. I had to open the SVGs that rendered off (they appeared clipped) using Illustrator and then removed the pieces that were causing the issues and re-exported. This project is actually no longer being used so I'll close this and archive the project.
